version: '3.4'

services:
  dockerhw.api:
    image: ${DOCKER_REGISTRY-}dockerhwapi
    build:
      context: .
      dockerfile: DockerHW.API/Dockerfile
    environment:
    - DATABASE_URL=server=localhost; port=5432; database=postgres; user id=postgres; password=password

  dockerhw.web:
    image: ${DOCKER_REGISTRY-}dockerhwweb
    build:
      context: .
      dockerfile: DockerHW.Web/Dockerfile
    environment: 
    - API_ADDRESS=http://dockerhw.api
    ports:
      - 5000:80

  database:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=admin
    ports:
    - 5432:5342
    expose:
    - 5432 